package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformCompany;
import cn.com.platform.platform.model.common.PlatformCompanyQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    long countByExample(PlatformCompanyQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformCompanyQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    List<PlatformCompany> selectByExample(PlatformCompanyQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformCompany record, @Param("example") PlatformCompanyQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformCompany record, @Param("example") PlatformCompanyQuery example);
}