package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformAdminUser;
import cn.com.platform.platform.model.common.PlatformAdminUserQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_user
     *
     * @mbg.generated
     */
    long countByExample(PlatformAdminUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_user
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformAdminUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_user
     *
     * @mbg.generated
     */
    List<PlatformAdminUser> selectByExample(PlatformAdminUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformAdminUser record, @Param("example") PlatformAdminUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformAdminUser record, @Param("example") PlatformAdminUserQuery example);
}