package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformOperateLog;
import cn.com.platform.platform.model.common.PlatformOperateLogQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    long countByExample(PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    List<PlatformOperateLog> selectByExampleWithBLOBs(PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    List<PlatformOperateLog> selectByExample(PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformOperateLog record, @Param("example") PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PlatformOperateLog record, @Param("example") PlatformOperateLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_operate_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformOperateLog record, @Param("example") PlatformOperateLogQuery example);
}