package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformMember;
import cn.com.platform.platform.model.common.PlatformMemberQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    long countByExample(PlatformMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    List<PlatformMember> selectByExample(PlatformMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformMember record, @Param("example") PlatformMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformMember record, @Param("example") PlatformMemberQuery example);
}