package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformJobRepeat;
import cn.com.platform.platform.model.common.PlatformJobRepeatQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformJobRepeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_repeat
     *
     * @mbg.generated
     */
    long countByExample(PlatformJobRepeatQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_repeat
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformJobRepeatQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_repeat
     *
     * @mbg.generated
     */
    List<PlatformJobRepeat> selectByExample(PlatformJobRepeatQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_repeat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformJobRepeat record, @Param("example") PlatformJobRepeatQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_repeat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformJobRepeat record, @Param("example") PlatformJobRepeatQuery example);
}