package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformJobLog;
import cn.com.platform.platform.model.common.PlatformJobLogQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformJobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    long countByExample(PlatformJobLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformJobLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    List<PlatformJobLog> selectByExample(PlatformJobLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformJobLog record, @Param("example") PlatformJobLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformJobLog record, @Param("example") PlatformJobLogQuery example);
}