package cn.com.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoPanoramaHotspot;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PanoPanoramaHotspotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hotspotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int insert(PanoPanoramaHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int insertSelective(PanoPanoramaHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    PanoPanoramaHotspot selectByPrimaryKey(String hotspotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PanoPanoramaHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PanoPanoramaHotspot record);
}