# 设定开发环境的文件
spring:
  # hot deploy
  devtools:
    restart:
      enabled: false

  # Datasource BaseSetting com.alibaba.druid.pool.DruidDataSource
  datasource:
    druid:
      #driverClassName: com.mysql.cj.jdbc.Driver
      driverClassName: net.sf.log4jdbc.DriverSpy
      # 数据库连接设定(default)
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /admin/monitor/druid/*
      filter:
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: false
          wall:
              config:
                  multi-statement-allow: true
                  
  # Datasource BaseSetting org.apache.tomcat.jdbc.pool.DataSource
  abstract.datasource:
    #driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: net.sf.log4jdbc.DriverSpy
    # 数据库连接设定(default)
    maxActive: 100
    maxIdle: 8
    minIdle: 8
    initialSize: 10
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    

  # 数据库链接参数设定
  datasource0000.datasource:
    #url: jdbc:mysql://120.78.13.166:3306/cis?characterEncoding=utf-8&useSSL=false
    url: jdbc:log4jdbc:mysql://localhost:3306/db_pano?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: panoadmin
    password: AAA111+++
    
  datasource0001.datasource:
    url: jdbc:mysql://localhost:3306/db_pano?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: panoadmin
    password: AAA111+++
      
  datasource0002.datasource:
    url: jdbc:mysql://localhost:3306/db_pano?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: panoadmin
    password: AAA111+++
