package cn.com.platform.platform.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PlatformJobLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.JOB_LOG_ID
     *
     * @mbg.generated
     */
    public String jobLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.JOB_ID
     *
     * @mbg.generated
     */
    public String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.JOB_NAME
     *
     * @mbg.generated
     */
    public String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.JOB_GROUP
     *
     * @mbg.generated
     */
    public String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.METHOD_NAME
     *
     * @mbg.generated
     */
    public String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.METHOD_PARAMS
     *
     * @mbg.generated
     */
    public String methodParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.JOB_MESSAGE
     *
     * @mbg.generated
     */
    public String jobMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.STATUS
     *
     * @mbg.generated
     */
    public String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.EXCEPTION_INFO
     *
     * @mbg.generated
     */
    public String exceptionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_job_log.CREATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}