package cn.com.platform.platform.model.common;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PlatformOnlineUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.SESSION_ID
     *
     * @mbg.generated
     */
    public String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.LOGIN_ID
     *
     * @mbg.generated
     */
    public String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.IP_ADDRESS
     *
     * @mbg.generated
     */
    public String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.LOGIN_ADDRESS
     *
     * @mbg.generated
     */
    public String loginAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.BROWSER
     *
     * @mbg.generated
     */
    public String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.OPERATING_SYSTEM
     *
     * @mbg.generated
     */
    public String operatingSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.STATUS
     *
     * @mbg.generated
     */
    public String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.START_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.LAST_ACCESS_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastAccessDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_online_user.EXPIRE_TIME
     *
     * @mbg.generated
     */
    public BigDecimal expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}