package cn.com.platform.platform.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PlatformCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.COMPANY_ID
     *
     * @mbg.generated
     */
    public String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.COMPANY_NAME
     *
     * @mbg.generated
     */
    public String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_company.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}