package cn.com.platform.platform.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PlatformMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_ID
     *
     * @mbg.generated
     */
    public String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_LOGIN_ID
     *
     * @mbg.generated
     */
    public String memberLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_NAME
     *
     * @mbg.generated
     */
    public String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_PASSWORD
     *
     * @mbg.generated
     */
    public String memberPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_EMAIL
     *
     * @mbg.generated
     */
    public String memberEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_PHONE
     *
     * @mbg.generated
     */
    public String memberPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_STATUS
     *
     * @mbg.generated
     */
    public String memberStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.MEMBER_IDENTIFICATION_STATE
     *
     * @mbg.generated
     */
    public String memberIdentificationState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_member.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}