package cn.com.platform.platform.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PlatformDepartmentUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    public String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.MEMBER_ID
     *
     * @mbg.generated
     */
    public String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_department_user.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}