package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoExpositionMap;
import cn.com.pano.pano.model.common.PanoExpositionMapQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoExpositionMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    long countByExample(PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    int deleteByExample(PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    List<PanoExpositionMap> selectByExampleWithBLOBs(PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    List<PanoExpositionMap> selectByExample(PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoExpositionMap record, @Param("example") PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PanoExpositionMap record, @Param("example") PanoExpositionMapQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoExpositionMap record, @Param("example") PanoExpositionMapQuery example);
}