package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoHotspotUrl;
import cn.com.pano.pano.model.common.PanoHotspotUrlQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoHotspotUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    long countByExample(PanoHotspotUrlQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int deleteByExample(PanoHotspotUrlQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    List<PanoHotspotUrl> selectByExample(PanoHotspotUrlQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoHotspotUrl record, @Param("example") PanoHotspotUrlQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoHotspotUrl record, @Param("example") PanoHotspotUrlQuery example);
}