package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoPanoramaHotspot;
import cn.com.pano.pano.model.common.PanoPanoramaHotspotQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoPanoramaHotspotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    long countByExample(PanoPanoramaHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int deleteByExample(PanoPanoramaHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    List<PanoPanoramaHotspot> selectByExample(PanoPanoramaHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoPanoramaHotspot record, @Param("example") PanoPanoramaHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoPanoramaHotspot record, @Param("example") PanoPanoramaHotspotQuery example);
}