package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoMaterial;
import cn.com.pano.pano.model.common.PanoMaterialQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    long countByExample(PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    int deleteByExample(PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    List<PanoMaterial> selectByExampleWithBLOBs(PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    List<PanoMaterial> selectByExample(PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoMaterial record, @Param("example") PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PanoMaterial record, @Param("example") PanoMaterialQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoMaterial record, @Param("example") PanoMaterialQuery example);
}