package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformMemberExtend;
import cn.com.platform.platform.model.common.PlatformMemberExtendQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformMemberExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    long countByExample(PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    List<PlatformMemberExtend> selectByExampleWithBLOBs(PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    List<PlatformMemberExtend> selectByExample(PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformMemberExtend record, @Param("example") PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PlatformMemberExtend record, @Param("example") PlatformMemberExtendQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_member_extend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformMemberExtend record, @Param("example") PlatformMemberExtendQuery example);
}