package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformRoleMenu;
import cn.com.platform.platform.model.common.PlatformRoleMenuQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_menu
     *
     * @mbg.generated
     */
    long countByExample(PlatformRoleMenuQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_menu
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformRoleMenuQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_menu
     *
     * @mbg.generated
     */
    List<PlatformRoleMenu> selectByExample(PlatformRoleMenuQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformRoleMenu record, @Param("example") PlatformRoleMenuQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformRoleMenu record, @Param("example") PlatformRoleMenuQuery example);
}