package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformDepartment;
import cn.com.platform.platform.model.common.PlatformDepartmentQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    long countByExample(PlatformDepartmentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformDepartmentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    List<PlatformDepartment> selectByExample(PlatformDepartmentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformDepartment record, @Param("example") PlatformDepartmentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformDepartment record, @Param("example") PlatformDepartmentQuery example);
}