package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformLoginInfo;
import cn.com.platform.platform.model.common.PlatformLoginInfoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_login_info
     *
     * @mbg.generated
     */
    long countByExample(PlatformLoginInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_login_info
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformLoginInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_login_info
     *
     * @mbg.generated
     */
    List<PlatformLoginInfo> selectByExample(PlatformLoginInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_login_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformLoginInfo record, @Param("example") PlatformLoginInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_login_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformLoginInfo record, @Param("example") PlatformLoginInfoQuery example);
}