package cn.com.example.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformOnlineUser;
import cn.com.platform.platform.model.common.PlatformOnlineUserQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformOnlineUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    long countByExample(PlatformOnlineUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformOnlineUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    List<PlatformOnlineUser> selectByExample(PlatformOnlineUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformOnlineUser record, @Param("example") PlatformOnlineUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformOnlineUser record, @Param("example") PlatformOnlineUserQuery example);
}