package cn.com.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoHotspotUrl;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoHotspotUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("hotspotId") String hotspotId, @Param("hotspotUrlObjectId") String hotspotUrlObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int insert(PanoHotspotUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int insertSelective(PanoHotspotUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    PanoHotspotUrl selectByPrimaryKey(@Param("hotspotId") String hotspotId, @Param("hotspotUrlObjectId") String hotspotUrlObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PanoHotspotUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_hotspot_url
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PanoHotspotUrl record);
}