package cn.com.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoProcessItems;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PanoProcessItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int insert(PanoProcessItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int insertSelective(PanoProcessItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    PanoProcessItems selectByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PanoProcessItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PanoProcessItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PanoProcessItems record);
}