package cn.com.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoPolygonHotspot;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PanoPolygonHotspotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String polygonPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int insert(PanoPolygonHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int insertSelective(PanoPolygonHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    PanoPolygonHotspot selectByPrimaryKey(String polygonPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PanoPolygonHotspot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PanoPolygonHotspot record);
}