package cn.com.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoGrpRoleUserTmpl;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PanoGrpRoleUserTmplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tmplId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int insert(PanoGrpRoleUserTmpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int insertSelective(PanoGrpRoleUserTmpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    PanoGrpRoleUserTmpl selectByPrimaryKey(String tmplId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PanoGrpRoleUserTmpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PanoGrpRoleUserTmpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_grp_role_user_tmpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PanoGrpRoleUserTmpl record);
}