package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformDepartmentUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformDepartmentUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("departmentId") String departmentId, @Param("memberId") String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    int insert(PlatformDepartmentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    int insertSelective(PlatformDepartmentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    PlatformDepartmentUser selectByPrimaryKey(@Param("departmentId") String departmentId, @Param("memberId") String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformDepartmentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformDepartmentUser record);
}