package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformDepartment;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("companyId") String companyId, @Param("departmentId") String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int insert(PlatformDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int insertSelective(PlatformDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    PlatformDepartment selectByPrimaryKey(@Param("companyId") String companyId, @Param("departmentId") String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformDepartment record);
}