package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformJobLog;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PlatformJobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String jobLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int insert(PlatformJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int insertSelective(PlatformJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    PlatformJobLog selectByPrimaryKey(String jobLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_job_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformJobLog record);
}