package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PlatformRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    int insert(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    int insertSelective(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    PlatformRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformRole record);
}