package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformAdminRoleUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlatformAdminRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") String roleId, @Param("adminId") String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    int insert(PlatformAdminRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    int insertSelective(PlatformAdminRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    PlatformAdminRoleUser selectByPrimaryKey(@Param("roleId") String roleId, @Param("adminId") String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformAdminRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformAdminRoleUser record);
}