package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformAdminRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PlatformAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    int insert(PlatformAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    int insertSelective(PlatformAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    PlatformAdminRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_admin_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformAdminRole record);
}