package cn.com.platform.platform.mapper.common;

import cn.com.platform.platform.model.common.PlatformOnlineUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PlatformOnlineUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int insert(PlatformOnlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int insertSelective(PlatformOnlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    PlatformOnlineUser selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformOnlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_online_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformOnlineUser record);
}