package cn.com.pano.pano.model.common;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PanoExposition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_id
     *
     * @mbg.generated
     */
    public String expositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_name
     *
     * @mbg.generated
     */
    public String expositionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_type
     *
     * @mbg.generated
     */
    public String expositionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.preload_file_path
     *
     * @mbg.generated
     */
    public String preloadFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.preload_file_type
     *
     * @mbg.generated
     */
    public String preloadFileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.flow_info_file_id
     *
     * @mbg.generated
     */
    public String flowInfoFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.flow_info_file_x
     *
     * @mbg.generated
     */
    public String flowInfoFileX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.flow_info_file_y
     *
     * @mbg.generated
     */
    public String flowInfoFileY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.flow_info_file_scale
     *
     * @mbg.generated
     */
    public String flowInfoFileScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_sound_id
     *
     * @mbg.generated
     */
    public String expositionSoundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_selected_buttons
     *
     * @mbg.generated
     */
    public String expositionSelectedButtons;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_recommend_info
     *
     * @mbg.generated
     */
    public String expositionRecommendInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.expo_go_scene_tooltip
     *
     * @mbg.generated
     */
    public String expoGoSceneTooltip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_start_date
     *
     * @mbg.generated
     */
    public LocalDate expositionStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_end_date
     *
     * @mbg.generated
     */
    public LocalDate expositionEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.exposition_folder_id
     *
     * @mbg.generated
     */
    public String expositionFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.status
     *
     * @mbg.generated
     */
    public String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.release_date
     *
     * @mbg.generated
     */
    public LocalDateTime releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.vr_flag
     *
     * @mbg.generated
     */
    public String vrFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.status_notes
     *
     * @mbg.generated
     */
    public String statusNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition.notes
     *
     * @mbg.generated
     */
    public String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}