package cn.com.pano.pano.model.common;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PanoPanoramaHotspotQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public PanoPanoramaHotspotQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotspotIdIsNull() {
            addCriterion("hotspot_id is null");
            return (Criteria) this;
        }

        public Criteria andHotspotIdIsNotNull() {
            addCriterion("hotspot_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotIdEqualTo(String value) {
            addCriterion("hotspot_id =", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdNotEqualTo(String value) {
            addCriterion("hotspot_id <>", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdGreaterThan(String value) {
            addCriterion("hotspot_id >", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_id >=", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdLessThan(String value) {
            addCriterion("hotspot_id <", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdLessThanOrEqualTo(String value) {
            addCriterion("hotspot_id <=", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdLike(String value) {
            addCriterion("hotspot_id like", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdNotLike(String value) {
            addCriterion("hotspot_id not like", value, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdIn(List<String> values) {
            addCriterion("hotspot_id in", values, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdNotIn(List<String> values) {
            addCriterion("hotspot_id not in", values, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdBetween(String value1, String value2) {
            addCriterion("hotspot_id between", value1, value2, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andHotspotIdNotBetween(String value1, String value2) {
            addCriterion("hotspot_id not between", value1, value2, "hotspotId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdIsNull() {
            addCriterion("panorama_id is null");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdIsNotNull() {
            addCriterion("panorama_id is not null");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdEqualTo(String value) {
            addCriterion("panorama_id =", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdNotEqualTo(String value) {
            addCriterion("panorama_id <>", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdGreaterThan(String value) {
            addCriterion("panorama_id >", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdGreaterThanOrEqualTo(String value) {
            addCriterion("panorama_id >=", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdLessThan(String value) {
            addCriterion("panorama_id <", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdLessThanOrEqualTo(String value) {
            addCriterion("panorama_id <=", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdLike(String value) {
            addCriterion("panorama_id like", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdNotLike(String value) {
            addCriterion("panorama_id not like", value, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdIn(List<String> values) {
            addCriterion("panorama_id in", values, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdNotIn(List<String> values) {
            addCriterion("panorama_id not in", values, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdBetween(String value1, String value2) {
            addCriterion("panorama_id between", value1, value2, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andPanoramaIdNotBetween(String value1, String value2) {
            addCriterion("panorama_id not between", value1, value2, "panoramaId");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleIsNull() {
            addCriterion("hotspot_scale is null");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleIsNotNull() {
            addCriterion("hotspot_scale is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleEqualTo(String value) {
            addCriterion("hotspot_scale =", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleNotEqualTo(String value) {
            addCriterion("hotspot_scale <>", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleGreaterThan(String value) {
            addCriterion("hotspot_scale >", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_scale >=", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleLessThan(String value) {
            addCriterion("hotspot_scale <", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleLessThanOrEqualTo(String value) {
            addCriterion("hotspot_scale <=", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleLike(String value) {
            addCriterion("hotspot_scale like", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleNotLike(String value) {
            addCriterion("hotspot_scale not like", value, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleIn(List<String> values) {
            addCriterion("hotspot_scale in", values, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleNotIn(List<String> values) {
            addCriterion("hotspot_scale not in", values, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleBetween(String value1, String value2) {
            addCriterion("hotspot_scale between", value1, value2, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotScaleNotBetween(String value1, String value2) {
            addCriterion("hotspot_scale not between", value1, value2, "hotspotScale");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeIsNull() {
            addCriterion("hotspot_type is null");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeIsNotNull() {
            addCriterion("hotspot_type is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeEqualTo(String value) {
            addCriterion("hotspot_type =", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeNotEqualTo(String value) {
            addCriterion("hotspot_type <>", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeGreaterThan(String value) {
            addCriterion("hotspot_type >", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_type >=", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeLessThan(String value) {
            addCriterion("hotspot_type <", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeLessThanOrEqualTo(String value) {
            addCriterion("hotspot_type <=", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeLike(String value) {
            addCriterion("hotspot_type like", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeNotLike(String value) {
            addCriterion("hotspot_type not like", value, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeIn(List<String> values) {
            addCriterion("hotspot_type in", values, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeNotIn(List<String> values) {
            addCriterion("hotspot_type not in", values, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeBetween(String value1, String value2) {
            addCriterion("hotspot_type between", value1, value2, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotTypeNotBetween(String value1, String value2) {
            addCriterion("hotspot_type not between", value1, value2, "hotspotType");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdIsNull() {
            addCriterion("hotspot_image_id is null");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdIsNotNull() {
            addCriterion("hotspot_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdEqualTo(String value) {
            addCriterion("hotspot_image_id =", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdNotEqualTo(String value) {
            addCriterion("hotspot_image_id <>", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdGreaterThan(String value) {
            addCriterion("hotspot_image_id >", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_image_id >=", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdLessThan(String value) {
            addCriterion("hotspot_image_id <", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdLessThanOrEqualTo(String value) {
            addCriterion("hotspot_image_id <=", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdLike(String value) {
            addCriterion("hotspot_image_id like", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdNotLike(String value) {
            addCriterion("hotspot_image_id not like", value, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdIn(List<String> values) {
            addCriterion("hotspot_image_id in", values, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdNotIn(List<String> values) {
            addCriterion("hotspot_image_id not in", values, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdBetween(String value1, String value2) {
            addCriterion("hotspot_image_id between", value1, value2, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andHotspotImageIdNotBetween(String value1, String value2) {
            addCriterion("hotspot_image_id not between", value1, value2, "hotspotImageId");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressIsNull() {
            addCriterion("external_link_address is null");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressIsNotNull() {
            addCriterion("external_link_address is not null");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressEqualTo(String value) {
            addCriterion("external_link_address =", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressNotEqualTo(String value) {
            addCriterion("external_link_address <>", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressGreaterThan(String value) {
            addCriterion("external_link_address >", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressGreaterThanOrEqualTo(String value) {
            addCriterion("external_link_address >=", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressLessThan(String value) {
            addCriterion("external_link_address <", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressLessThanOrEqualTo(String value) {
            addCriterion("external_link_address <=", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressLike(String value) {
            addCriterion("external_link_address like", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressNotLike(String value) {
            addCriterion("external_link_address not like", value, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressIn(List<String> values) {
            addCriterion("external_link_address in", values, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressNotIn(List<String> values) {
            addCriterion("external_link_address not in", values, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressBetween(String value1, String value2) {
            addCriterion("external_link_address between", value1, value2, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andExternalLinkAddressNotBetween(String value1, String value2) {
            addCriterion("external_link_address not between", value1, value2, "externalLinkAddress");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeIsNull() {
            addCriterion("hotspot_url_type is null");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeIsNotNull() {
            addCriterion("hotspot_url_type is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeEqualTo(String value) {
            addCriterion("hotspot_url_type =", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeNotEqualTo(String value) {
            addCriterion("hotspot_url_type <>", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeGreaterThan(String value) {
            addCriterion("hotspot_url_type >", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_url_type >=", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeLessThan(String value) {
            addCriterion("hotspot_url_type <", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeLessThanOrEqualTo(String value) {
            addCriterion("hotspot_url_type <=", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeLike(String value) {
            addCriterion("hotspot_url_type like", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeNotLike(String value) {
            addCriterion("hotspot_url_type not like", value, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeIn(List<String> values) {
            addCriterion("hotspot_url_type in", values, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeNotIn(List<String> values) {
            addCriterion("hotspot_url_type not in", values, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeBetween(String value1, String value2) {
            addCriterion("hotspot_url_type between", value1, value2, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andHotspotUrlTypeNotBetween(String value1, String value2) {
            addCriterion("hotspot_url_type not between", value1, value2, "hotspotUrlType");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdIsNull() {
            addCriterion("next_recommend_hotspot_id is null");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdIsNotNull() {
            addCriterion("next_recommend_hotspot_id is not null");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdEqualTo(String value) {
            addCriterion("next_recommend_hotspot_id =", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdNotEqualTo(String value) {
            addCriterion("next_recommend_hotspot_id <>", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdGreaterThan(String value) {
            addCriterion("next_recommend_hotspot_id >", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdGreaterThanOrEqualTo(String value) {
            addCriterion("next_recommend_hotspot_id >=", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdLessThan(String value) {
            addCriterion("next_recommend_hotspot_id <", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdLessThanOrEqualTo(String value) {
            addCriterion("next_recommend_hotspot_id <=", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdLike(String value) {
            addCriterion("next_recommend_hotspot_id like", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdNotLike(String value) {
            addCriterion("next_recommend_hotspot_id not like", value, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdIn(List<String> values) {
            addCriterion("next_recommend_hotspot_id in", values, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdNotIn(List<String> values) {
            addCriterion("next_recommend_hotspot_id not in", values, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdBetween(String value1, String value2) {
            addCriterion("next_recommend_hotspot_id between", value1, value2, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andNextRecommendHotspotIdNotBetween(String value1, String value2) {
            addCriterion("next_recommend_hotspot_id not between", value1, value2, "nextRecommendHotspotId");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoIsNull() {
            addCriterion("recommend_info is null");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoIsNotNull() {
            addCriterion("recommend_info is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoEqualTo(String value) {
            addCriterion("recommend_info =", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoNotEqualTo(String value) {
            addCriterion("recommend_info <>", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoGreaterThan(String value) {
            addCriterion("recommend_info >", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoGreaterThanOrEqualTo(String value) {
            addCriterion("recommend_info >=", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoLessThan(String value) {
            addCriterion("recommend_info <", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoLessThanOrEqualTo(String value) {
            addCriterion("recommend_info <=", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoLike(String value) {
            addCriterion("recommend_info like", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoNotLike(String value) {
            addCriterion("recommend_info not like", value, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoIn(List<String> values) {
            addCriterion("recommend_info in", values, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoNotIn(List<String> values) {
            addCriterion("recommend_info not in", values, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoBetween(String value1, String value2) {
            addCriterion("recommend_info between", value1, value2, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andRecommendInfoNotBetween(String value1, String value2) {
            addCriterion("recommend_info not between", value1, value2, "recommendInfo");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipIsNull() {
            addCriterion("hotspot_tooltip is null");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipIsNotNull() {
            addCriterion("hotspot_tooltip is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipEqualTo(String value) {
            addCriterion("hotspot_tooltip =", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipNotEqualTo(String value) {
            addCriterion("hotspot_tooltip <>", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipGreaterThan(String value) {
            addCriterion("hotspot_tooltip >", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_tooltip >=", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipLessThan(String value) {
            addCriterion("hotspot_tooltip <", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipLessThanOrEqualTo(String value) {
            addCriterion("hotspot_tooltip <=", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipLike(String value) {
            addCriterion("hotspot_tooltip like", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipNotLike(String value) {
            addCriterion("hotspot_tooltip not like", value, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipIn(List<String> values) {
            addCriterion("hotspot_tooltip in", values, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipNotIn(List<String> values) {
            addCriterion("hotspot_tooltip not in", values, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipBetween(String value1, String value2) {
            addCriterion("hotspot_tooltip between", value1, value2, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotTooltipNotBetween(String value1, String value2) {
            addCriterion("hotspot_tooltip not between", value1, value2, "hotspotTooltip");
            return (Criteria) this;
        }

        public Criteria andHotspotAthIsNull() {
            addCriterion("hotspot_ath is null");
            return (Criteria) this;
        }

        public Criteria andHotspotAthIsNotNull() {
            addCriterion("hotspot_ath is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotAthEqualTo(String value) {
            addCriterion("hotspot_ath =", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthNotEqualTo(String value) {
            addCriterion("hotspot_ath <>", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthGreaterThan(String value) {
            addCriterion("hotspot_ath >", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_ath >=", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthLessThan(String value) {
            addCriterion("hotspot_ath <", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthLessThanOrEqualTo(String value) {
            addCriterion("hotspot_ath <=", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthLike(String value) {
            addCriterion("hotspot_ath like", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthNotLike(String value) {
            addCriterion("hotspot_ath not like", value, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthIn(List<String> values) {
            addCriterion("hotspot_ath in", values, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthNotIn(List<String> values) {
            addCriterion("hotspot_ath not in", values, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthBetween(String value1, String value2) {
            addCriterion("hotspot_ath between", value1, value2, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAthNotBetween(String value1, String value2) {
            addCriterion("hotspot_ath not between", value1, value2, "hotspotAth");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvIsNull() {
            addCriterion("hotspot_atv is null");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvIsNotNull() {
            addCriterion("hotspot_atv is not null");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvEqualTo(String value) {
            addCriterion("hotspot_atv =", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvNotEqualTo(String value) {
            addCriterion("hotspot_atv <>", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvGreaterThan(String value) {
            addCriterion("hotspot_atv >", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvGreaterThanOrEqualTo(String value) {
            addCriterion("hotspot_atv >=", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvLessThan(String value) {
            addCriterion("hotspot_atv <", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvLessThanOrEqualTo(String value) {
            addCriterion("hotspot_atv <=", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvLike(String value) {
            addCriterion("hotspot_atv like", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvNotLike(String value) {
            addCriterion("hotspot_atv not like", value, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvIn(List<String> values) {
            addCriterion("hotspot_atv in", values, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvNotIn(List<String> values) {
            addCriterion("hotspot_atv not in", values, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvBetween(String value1, String value2) {
            addCriterion("hotspot_atv between", value1, value2, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andHotspotAtvNotBetween(String value1, String value2) {
            addCriterion("hotspot_atv not between", value1, value2, "hotspotAtv");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatIsNull() {
            addCriterion("panorama_hlookat is null");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatIsNotNull() {
            addCriterion("panorama_hlookat is not null");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatEqualTo(String value) {
            addCriterion("panorama_hlookat =", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatNotEqualTo(String value) {
            addCriterion("panorama_hlookat <>", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatGreaterThan(String value) {
            addCriterion("panorama_hlookat >", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatGreaterThanOrEqualTo(String value) {
            addCriterion("panorama_hlookat >=", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatLessThan(String value) {
            addCriterion("panorama_hlookat <", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatLessThanOrEqualTo(String value) {
            addCriterion("panorama_hlookat <=", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatLike(String value) {
            addCriterion("panorama_hlookat like", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatNotLike(String value) {
            addCriterion("panorama_hlookat not like", value, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatIn(List<String> values) {
            addCriterion("panorama_hlookat in", values, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatNotIn(List<String> values) {
            addCriterion("panorama_hlookat not in", values, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatBetween(String value1, String value2) {
            addCriterion("panorama_hlookat between", value1, value2, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaHlookatNotBetween(String value1, String value2) {
            addCriterion("panorama_hlookat not between", value1, value2, "panoramaHlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatIsNull() {
            addCriterion("panorama_vlookat is null");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatIsNotNull() {
            addCriterion("panorama_vlookat is not null");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatEqualTo(String value) {
            addCriterion("panorama_vlookat =", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatNotEqualTo(String value) {
            addCriterion("panorama_vlookat <>", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatGreaterThan(String value) {
            addCriterion("panorama_vlookat >", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatGreaterThanOrEqualTo(String value) {
            addCriterion("panorama_vlookat >=", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatLessThan(String value) {
            addCriterion("panorama_vlookat <", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatLessThanOrEqualTo(String value) {
            addCriterion("panorama_vlookat <=", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatLike(String value) {
            addCriterion("panorama_vlookat like", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatNotLike(String value) {
            addCriterion("panorama_vlookat not like", value, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatIn(List<String> values) {
            addCriterion("panorama_vlookat in", values, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatNotIn(List<String> values) {
            addCriterion("panorama_vlookat not in", values, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatBetween(String value1, String value2) {
            addCriterion("panorama_vlookat between", value1, value2, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPanoramaVlookatNotBetween(String value1, String value2) {
            addCriterion("panorama_vlookat not between", value1, value2, "panoramaVlookat");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorIsNull() {
            addCriterion("polygon_fillcolor is null");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorIsNotNull() {
            addCriterion("polygon_fillcolor is not null");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorEqualTo(String value) {
            addCriterion("polygon_fillcolor =", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorNotEqualTo(String value) {
            addCriterion("polygon_fillcolor <>", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorGreaterThan(String value) {
            addCriterion("polygon_fillcolor >", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorGreaterThanOrEqualTo(String value) {
            addCriterion("polygon_fillcolor >=", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorLessThan(String value) {
            addCriterion("polygon_fillcolor <", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorLessThanOrEqualTo(String value) {
            addCriterion("polygon_fillcolor <=", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorLike(String value) {
            addCriterion("polygon_fillcolor like", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorNotLike(String value) {
            addCriterion("polygon_fillcolor not like", value, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorIn(List<String> values) {
            addCriterion("polygon_fillcolor in", values, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorNotIn(List<String> values) {
            addCriterion("polygon_fillcolor not in", values, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorBetween(String value1, String value2) {
            addCriterion("polygon_fillcolor between", value1, value2, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillcolorNotBetween(String value1, String value2) {
            addCriterion("polygon_fillcolor not between", value1, value2, "polygonFillcolor");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaIsNull() {
            addCriterion("polygon_fillalpha is null");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaIsNotNull() {
            addCriterion("polygon_fillalpha is not null");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaEqualTo(String value) {
            addCriterion("polygon_fillalpha =", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaNotEqualTo(String value) {
            addCriterion("polygon_fillalpha <>", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaGreaterThan(String value) {
            addCriterion("polygon_fillalpha >", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaGreaterThanOrEqualTo(String value) {
            addCriterion("polygon_fillalpha >=", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaLessThan(String value) {
            addCriterion("polygon_fillalpha <", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaLessThanOrEqualTo(String value) {
            addCriterion("polygon_fillalpha <=", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaLike(String value) {
            addCriterion("polygon_fillalpha like", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaNotLike(String value) {
            addCriterion("polygon_fillalpha not like", value, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaIn(List<String> values) {
            addCriterion("polygon_fillalpha in", values, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaNotIn(List<String> values) {
            addCriterion("polygon_fillalpha not in", values, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaBetween(String value1, String value2) {
            addCriterion("polygon_fillalpha between", value1, value2, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andPolygonFillalphaNotBetween(String value1, String value2) {
            addCriterion("polygon_fillalpha not between", value1, value2, "polygonFillalpha");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(LocalDateTime value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(LocalDateTime value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIsNull() {
            addCriterion("LAST_UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIsNotNull() {
            addCriterion("LAST_UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdEqualTo(String value) {
            addCriterion("LAST_UPDATE_USER_ID =", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotEqualTo(String value) {
            addCriterion("LAST_UPDATE_USER_ID <>", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdGreaterThan(String value) {
            addCriterion("LAST_UPDATE_USER_ID >", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATE_USER_ID >=", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdLessThan(String value) {
            addCriterion("LAST_UPDATE_USER_ID <", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATE_USER_ID <=", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdLike(String value) {
            addCriterion("LAST_UPDATE_USER_ID like", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotLike(String value) {
            addCriterion("LAST_UPDATE_USER_ID not like", value, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdIn(List<String> values) {
            addCriterion("LAST_UPDATE_USER_ID in", values, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotIn(List<String> values) {
            addCriterion("LAST_UPDATE_USER_ID not in", values, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdBetween(String value1, String value2) {
            addCriterion("LAST_UPDATE_USER_ID between", value1, value2, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("LAST_UPDATE_USER_ID not between", value1, value2, "lastUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pano_panorama_hotspot
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}