package cn.com.pano.pano.model.common;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PanoExpositionMap implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_map_id
     *
     * @mbg.generated
     */
    public String expositionMapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_id
     *
     * @mbg.generated
     */
    public String expositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_map_use_state
     *
     * @mbg.generated
     */
    public String expositionMapUseState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_map_name
     *
     * @mbg.generated
     */
    public String expositionMapName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_map_path
     *
     * @mbg.generated
     */
    public String expositionMapPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.exposition_map_sort_key
     *
     * @mbg.generated
     */
    public BigDecimal expositionMapSortKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_exposition_map.notes
     *
     * @mbg.generated
     */
    public String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_exposition_map
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}