package cn.com.pano.pano.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PanoGroupRoleUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.group_id
     *
     * @mbg.generated
     */
    public String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.role_id
     *
     * @mbg.generated
     */
    public String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.user_id
     *
     * @mbg.generated
     */
    public String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.start_date
     *
     * @mbg.generated
     */
    public String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.end_date
     *
     * @mbg.generated
     */
    public String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_group_role_user.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_group_role_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}