package cn.com.platform.platform.mapper.common01;

import java.util.List;
import cn.com.platform.platform.mapper.common.PlatformRoleUserMapper;
import cn.com.platform.platform.model.common.PlatformRoleUser;
import cn.com.platform.platform.model.common.PlatformRoleUserQuery;

public interface PlatformRoleUser01Mapper extends PlatformRoleUserMapper {

  /**
   * 通过基础model删除数据
   *
   * @mbg.generated
   */
  int deleteByBaseModel(PlatformRoleUserQuery example);

  /**
   * 通过基础model检索数据
   *
   * @mbg.generated
   */
  List<PlatformRoleUser> selectByBaseModel(PlatformRoleUserQuery example);
  /**
   * 伦理删除角色-用户表
   * 
   * @param memberId
   */
  void deleteByRoleUserId(String memberId);
  
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table Platform_role_user
   *
   * @mbg.generated
   */
  int updateByPrimary01Query(PlatformRoleUserQuery example);
}