package cn.com.pano.pano.model.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PanoProcessItems implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.process_id
     *
     * @mbg.generated
     */
    public String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.type_id
     *
     * @mbg.generated
     */
    public String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.user_id
     *
     * @mbg.generated
     */
    public String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.summary
     *
     * @mbg.generated
     */
    public String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.parameter1
     *
     * @mbg.generated
     */
    public String parameter1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.parameter2
     *
     * @mbg.generated
     */
    public String parameter2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.parameter3
     *
     * @mbg.generated
     */
    public String parameter3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.parameter4
     *
     * @mbg.generated
     */
    public String parameter4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.parameter5
     *
     * @mbg.generated
     */
    public String parameter5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.deadline
     *
     * @mbg.generated
     */
    public String deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.process_flag
     *
     * @mbg.generated
     */
    public String processFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.priority
     *
     * @mbg.generated
     */
    public String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.DELETE_FLAG
     *
     * @mbg.generated
     */
    public Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.LAST_UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pano_process_items.notes
     *
     * @mbg.generated
     */
    public String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}