package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoProcessItems;
import cn.com.pano.pano.model.common.PanoProcessItemsQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoProcessItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    long countByExample(PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int deleteByExample(PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    List<PanoProcessItems> selectByExampleWithBLOBs(PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    List<PanoProcessItems> selectByExample(PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoProcessItems record, @Param("example") PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PanoProcessItems record, @Param("example") PanoProcessItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_process_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoProcessItems record, @Param("example") PanoProcessItemsQuery example);
}