package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoPanorama;
import cn.com.pano.pano.model.common.PanoPanoramaQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoPanoramaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    long countByExample(PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    int deleteByExample(PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    List<PanoPanorama> selectByExampleWithBLOBs(PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    List<PanoPanorama> selectByExample(PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoPanorama record, @Param("example") PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PanoPanorama record, @Param("example") PanoPanoramaQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_panorama
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoPanorama record, @Param("example") PanoPanoramaQuery example);
}