package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoExposition;
import cn.com.pano.pano.model.common.PanoExpositionQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoExpositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    long countByExample(PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    int deleteByExample(PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    List<PanoExposition> selectByExampleWithBLOBs(PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    List<PanoExposition> selectByExample(PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoExposition record, @Param("example") PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PanoExposition record, @Param("example") PanoExpositionQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_exposition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoExposition record, @Param("example") PanoExpositionQuery example);
}