package cn.com.example.pano.pano.mapper.common;

import cn.com.pano.pano.model.common.PanoPolygonHotspot;
import cn.com.pano.pano.model.common.PanoPolygonHotspotQuery;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PanoPolygonHotspotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    long countByExample(PanoPolygonHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int deleteByExample(PanoPolygonHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    List<PanoPolygonHotspot> selectByExample(PanoPolygonHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PanoPolygonHotspot record, @Param("example") PanoPolygonHotspotQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_polygon_hotspot
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PanoPolygonHotspot record, @Param("example") PanoPolygonHotspotQuery example);
}